from django.urls import path
from . import views

urlpatterns = [
    # path('login/',views.login),
    # path('logout/', views.logout),
    path('home/', views.homepage),
    path('history/', views.history),
    path('download/', views.download_file),
    path('downloadHistory/', views.download_history, name='download_history'),
    path('templateStudent/', views.download_student, name='download_student'),
    path('templateEnrollment/', views.download_enrollment, name='download_enrollment'),
    path('templateGrade/', views.download_grade, name='download_grade'),
    path('templateStatus/', views.download_status, name='download_status'),
    path('templateState/', views.download_state, name='download_state'),
    path('templateCourse/', views.download_course, name='download_course'),
    path('templateApptype/', views.download_appType, name='download_appType'),
    path('templatePlan/', views.download_plan, name='download_plan'),
    path('uploadfile/', views.upload_file, name='upload_file'),
    path('checkdata/', views.check_data, name='check_data'),
    path('confirmfile/', views.confirm_file, name='confirm_file'),
    path('createStudent/', views.create_student, name='create_student'),
    path('createCourseUsage/', views.create_courseUsage, name='create_courseUsage'),
    path('createApptype/', views.create_appType, name='create_appType'),
    # path('createPlan/', views.create_plan, name='create_plan'),
    path('editStudent/', views.search_student, name='edit_student'),
    path('updateStudent/<int:id>', views.update_student, name='update_student'),
    path('editEnrollment/', views.search_enrollment, name='edit_enrollment'),
    path('updateEnrollment/<int:id>', views.update_enrollment, name='update_enrollment'),
    path('editGrade/', views.search_grade, name='edit_grade'),
    path('updateGrade/<int:id>', views.update_grade, name='update_grade'),
    path('editState/', views.search_state, name='edit_state'),
    path('updateState/<int:id>', views.update_state, name='update_state'),
    path('editCourseUsage/', views.search_courseUsage, name='edit_courseUsage'),
    path('updateCourseUsage/<int:id>', views.update_courseUsage, name='update_courseUsage'),
    path('editApptype/', views.search_appType, name='edit_appType'),
    path('updateApptype/<int:id>', views.update_appType, name='update_appType'),
    path('editPlan/', views.search_plan, name='edit_plan'),
    path('updatePlan/<int:id>', views.update_plan, name='update_plan'),
    path('english/', views.eng_efficiency),
    path('requiredC/', views.requiredC),
    path('passCS300/', views.pass_CS300),
    path('basic/', views.basic),
    path('highschoolPlan/', views.highschool_plan),
    path('admitType/', views.admit_type),
    path('presentStudent/', views.student_now),
    path('processPlan/', views.process_plan),
    path('ajax/load-subapptype/', views.load_subapptype, name='ajax_load_subapptype'), # AJAX
]